version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - mysql-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      zookeeper:
        condition: service_started
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1   
    ports:
      - "9092:9092"
    networks:
      - mysql-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=chatapp
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql

  laravel:
    image: ayoubmouhssine1/chat-app:laravel
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: chatapp
      DB_USERNAME: root
      DB_PASSWORD: root
      KAFKA_BROKER: kafka:9092
    volumes:
      - ../storage/app:/var/www/html/storage/app
      - ../storage/app/public/avatars:/var/www/html/public/storage/avatars
    networks:
      - mysql-network
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy

  springboot:
    image: ayoubmouhssine1/chat-app:springboot
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/chatapp
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - mysql-network
    depends_on:
      db:
        condition: service_healthy

  express:
    image: ayoubmouhssine1/chat-app:express
    ports:
      - "3500:3500"
    environment:
      - PORT=3500
      - KAFKA_BROKER=kafka:9092
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=ayoub.mouhssine00@gmail.com
      - SMTP_PASSWORD=ohezdumabpirdwcn
      - EMAIL_FROM=noreply@securechat.com
    volumes:
      - ./backend3-express:/usr/src/app
    depends_on:
      kafka:
        condition: service_started
    networks:
      - mysql-network

  frontend:
    image: ayoubmouhssine1/chat-app:frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - mysql-network

volumes:
  db_data:

networks:
  mysql-network:
    name: mysql-network
